name: Push to main

on:
  push:
    tags:
      - '*.*.*'

jobs:
  Build-Push-Docker-Hub:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU to provide multiple architectures
        uses: docker/setup-qemu-action@v2

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx to build for multiple architectures
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push multi-architecture images
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: voquis/local-openapi-aws-rest-api-gateway-lambda:${{ github.ref_name }}
