name: Push to main

on:
  push:
    tags:
      - '*.*.*'

jobs:
  Build-Push-Docker-Hub:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU to provide multiple architectures
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx to build for multiple architectures
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push multi-architecture images
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms:
            - linux/amd64
            - linux/arm64
          push: true
          tags:
            - voquis/local-openapi-aws-rest-api-gateway-lambda:${{ github.ref_name }}
            - voquis/local-openapi-aws-rest-api-gateway-lambda:latest
